### ISSUE TITLE
Create HackMD for Oct 2023 training session

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy-demos#68]

**Comment by nabriis** [comment]
I went through the HackMD and updates a few very minor things. It looks really good. Things for you. @jakobsj 

1) I added "End of Day 1" and "End of Day 2" to the programme with ??:?? time slots. This was mostly to give a clear guidance when the official event ends, Can you add the times?
2) Update the learnmore section with instructions if they can now use DTU logins.
3) Update link to feedback form

**Comment by amal-ghamdi** [comment]
Thank you @jakobsj for preparing the hackmd. I took a very quick look and I think it looks great! just needs the few updates @nabriis mentioned I believe.
